# ~6GB VRAM: Qwen2.5-3B — use fewer scenes and lower temperature for JSON reliability.
# For consistent stage 3+ JSON, prefer script_setup_12gb.yaml (Qwen3-4B-AWQ).
global_vllm_config:
  model_path: Qwen/Qwen2.5-3B-Instruct
  quantization: none
  dtype: float16
  max_tokens: 3072
  temperature: 0.35
  top_p: 0.95
  top_k: 20
  min_p: 0
  max_model_len: 4096
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.90
  enforce_eager: false
  enable_thinking: false
  max_num_seqs: 1
  max_num_batched_tokens: 4096

idea_config:
  num_ideas: 1
  prompt_path: script_setup/prompts/stage_1.md
  output_path: data/
  batch_size: 0

title_config:
  num_words: 5
  prompt_path: script_setup/prompts/stage_2.md
  script_path: data/
  batch_size: 1

scene_config:
  num_scenes: 3
  prompt_path: script_setup/prompts/stage_3.md
  script_path: data/
  batch_size: 1

scene_content_config:
  min_beats: 6
  max_beats: 10
  prompt_path: script_setup/prompts/stage_4.md
  script_path: data/
  batch_size: 1

image_config:
  min_prompts: 1
  max_prompts: 3
  prompt_path: script_setup/prompts/stage_5.md
  script_path: data/
  batch_size: 1
